baseurl = "https://napcodes.github.io/theperrylife/"
languageCode = "en-us"
theme = "jekyll"
paginate = 5
publishDir = "docs"
themesDir = "themes"
[Menus]
main = [
  {Name = "Github(ext)", URL = "https://github.com/napcodes"},
  {Name = "About Me", URL = "http://www.theperrylife.com"}
]
[params]
  Title = "Nick Perry"
  description = "Welcome to the club"
  themeColor = "theme-base-0d"
  layoutReverse = "true"
  disqusShortname = "spf13"
